### ISSUE TITLE
Helper functions for making requests against interactive API jobs

### ISSUE THREAD

**Issue by mortenpi** [JuliaComputing/JuliaHub.jl#14]
When you start an interactive job that exposes an HTTP API, you have to manage a few things when trying to make requests to it from Julia:

1. You probably have to authenticate (either with a token or a password). This means adding an `Authorization` header.
2. You need to know the random URL of the job.

Managing this by hand can get tedious, so we could offer some helper API here that takes care of most of it for you automatically.

One option is to offer overloads of the HTTP.jl methods. So it might look something like:

```julia
endpoint::JuliaHub.JobEndpoint = JuliaHub.job_endpoint(job; auth)
# HTTP.request("GET", endpoint, path::String, [[, headers], body]), e.g.:
HTTP.request("GET", endpoint, "/my/rest/path")
```

Or possibly just offer our own `JuliaHub.request` function. Another suggestion was to allow the users to construct a callable object like

```julia
request = JuliaHub.interactive_requests(job; auth)
request("GET", "/my/rest/path", [[headers], body] )
```

cc @pfitzseb @pankgeorg

**Comment by pmodv** [comment]
This enhancement would be relevant for Planview, as they will be doing this, at scale.
