### ISSUE TITLE
Source file not found in appbundle jobs

### ISSUE THREAD

**Issue by jvaverka** [JuliaComputing/JuliaHub.jl#37]
**Description**

I followed the instructions for submitting [batch jobs via an appbundle](https://help.juliahub.com/julia-api/stable/guides/jobs/#jobs-batch-appbundles). My main `codefile` includes a single julia file with function definitions and then executes function calls. The job fails when calling `include` because the julia file with function definitions cannot be found. Since the job was submitted as an `appbundle`, I am expecting the `codefile` to be able to include other source files within the `appbundle` `directory`.

**To Reproduce**

Clone the [MWE repo](https://github.com/jvaverka/julia-in-a-nutshell) and run `submit.jl`. The job will fail with the following message:

```
LoadError: SystemError: opening file "/opt/juliahub/common.jl": No such file or directory
```

Full job lob: [Log for jr-awf3mbo64g.json](https://github.com/JuliaComputing/JuliaHub.jl/files/12882212/Log.for.jr-awf3mbo64g.json)

**Environment**

- **Where**: This happening in a JuliaHub IDE when submitting a JuliaHub batch job?
- **JuliaHub.jl version**: `v0.1.4`
- **Relevant JuliaHub instance:** `juliahub.com`
- **Julia version**: `v1.9.2`
- **Operating system**: Linux

**Comment by jvaverka** [comment]
I have also tested locally with the most recent version of `JuliaHub.jl`. Same source code and same error, but slightly different environment:

**Environment**

- **Where**: This is happening on my local machine
- **JuliaHub.jl version**: `v0.1.5`
- **Relevant JuliaHub instance**: <juliahub.com> `v6.3.1`
- **Julia version**: `v1.9.3`
- **Operating system**: Ubuntu 22.04.3 LTS

**Comment by mortenpi** [comment]
I'd say that this is working as expected. Conceptually, the appbundle gets unpacked as:

```
main.jl
appbundle/common.jl
```

#53 will clarify the docs around this a bit.
